# Generated by Django 4.2 on 2023-04-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_useraccess_remove_userboolean_boolean_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccess',
            options={'verbose_name': 'Пользовательский доступ', 'verbose_name_plural': 'Пользовательский доступ'},
        ),
    ]
