# Generated by Django 4.2 on 2023-04-30 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_useraccess_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата, время')),
                ('ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='IP')),
                ('client', models.CharField(blank=True, max_length=60, null=True, verbose_name='Клиент')),
                ('device_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель устройства')),
                ('app_version', models.CharField(blank=True, max_length=10, null=True, verbose_name='Версия App')),
                ('token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Token')),
                ('received', models.CharField(blank=True, max_length=50, null=True, verbose_name='Получено')),
                ('transferred', models.CharField(blank=True, max_length=50, null=True, verbose_name='Передано')),
                ('access', models.BooleanField(default=False, verbose_name='Доступ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
            },
        ),
    ]
