# Generated by Django 4.2 on 2023-05-01 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTimeout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_timeout', models.PositiveIntegerField(default=30, verbose_name='Таймаут сессии (сек)')),
            ],
            options={
                'verbose_name': 'Таймаут сессии (сек)',
                'verbose_name_plural': 'Таймаут сессии (сек)',
            },
        ),
        migrations.CreateModel(
            name='ServerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес сервера')),
                ('server_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пароль сервера')),
                ('dns', models.CharField(blank=True, max_length=40, null=True, verbose_name='DNS')),
                ('ip', models.CharField(blank=True, max_length=40, null=True, verbose_name='IP')),
                ('https', models.CharField(blank=True, max_length=40, null=True, verbose_name='HTTPS')),
                ('ssl', models.CharField(blank=True, max_length=50, null=True, verbose_name='SSL')),
                ('session_timeout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.sessiontimeout', verbose_name='Таймаут сессии (сек)')),
            ],
            options={
                'verbose_name': 'Настройки сервера',
                'verbose_name_plural': 'Настройки сервера',
            },
        ),
    ]
