# Generated by Django 4.2 on 2023-05-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_sessiontimeout_serversettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversettings',
            name='status_server',
            field=models.BooleanField(blank=True, null=True, verbose_name='Сервер состояния'),
        ),
    ]
